---
- name: Playbook for role testing - container
  hosts: all
  connection: paramiko

  vars:
    ansible_ssh_user: dragon
    openstackclient_install_type: container

  roles:
    - role: ansible-openstackclient

- name: Playbook for role testing - package
  hosts: all
  connection: paramiko

  vars:
    ansible_ssh_user: dragon
    openstackclient_install_type: package
    openstackclient_configure_repository: yes

  roles:
    - role: ansible-openstackclient
